#!/usr/bin/env python3
"""Render bench/results/RESULTS.md from the zkSync receipt measurements.

Reads qca-zksync-receipts.json (written by aa_flow.mjs via measure_zksync.sh)
and env.txt. Emits a Markdown report. The one load-bearing caveat, stated up
front: zkSync "gas" is NOT the same unit as L1 gas. It is an ergs-derived charge
that folds in state-diff pubdata, so these numbers must not be lined up against
the L1 receipt-gas tables in ../contracts. What this measurement establishes is
(1) the native-AA reveal actually validates and executes end to end on a real
node, exercising the NonceHolder path the unit tests skip, and (2) how the cost
scales with tree depth.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
RESULTS = HERE / "results"


def load():
    data = json.loads((RESULTS / "qca-zksync-receipts.json").read_text())
    env = (RESULTS / "env.txt").read_text().strip() if (RESULTS / "env.txt").exists() else "(env.txt not generated)"
    return data, env


def fmt(n):
    return f"{int(n):,}"


def main():
    data, env = load()
    depths = data["depths"]
    keys = sorted(depths, key=int)

    out = []
    out.append("# zkSync Era native-AA gas measurements\n")
    out.append("Generated by bench/report.py from bench/measure_zksync.sh. Environment:\n")
    out.append("```")
    out.append(env)
    out.append(f"chainId      {data['chainId']}")
    out.append("```\n")

    out.append(
        "**These numbers are zkSync gas, which is not the same unit as L1 gas.** "
        "zkSync charges an ergs-derived amount that folds in the pubdata cost of the "
        "transaction's state diff, so a reveal here is not comparable, digit for digit, "
        "to the L1 receipt-gas tables in `../contracts/bench`. The point of this harness "
        "is not a cheaper number. It is the existence proof: a type-0x71 transaction from "
        "`QCAAccountZkSync` validates and executes end to end on a real node, with no "
        "ECDSA anywhere on the authorization path and no ERC-4337 bundler relocating the "
        "envelope. The forge `--zksync` unit tests cannot show this because their VM does "
        "not run the bootloader / NonceHolder validation path; this does.\n"
    )

    out.append("## Receipt gas per transaction\n")
    out.append("| depth | commit | reveal (authorization only) | reveal (1 ETH action) |")
    out.append("|---|---|---|---|")
    for k in keys:
        d = depths[k]
        out.append(
            f"| {k} | {fmt(d['authOnly']['commitGasUsed'])} | "
            f"{fmt(d['authOnly']['revealGasUsed'])} | {fmt(d['action']['revealGasUsed'])} |"
        )
    out.append("")

    base = data.get("ecdsaBaseline")
    if base:
        ba = int(base["authOnly"]["gasUsed"])
        bx = int(base["action"]["gasUsed"])
        d16 = depths.get("16", depths[keys[len(keys) // 2]])
        ra = int(d16["authOnly"]["revealGasUsed"])
        rx = int(d16["action"]["revealGasUsed"])
        out.append("## Versus the ECDSA baseline\n")
        out.append(
            "A zkSync EOA is the `DefaultAccount` system contract, which verifies a secp256k1 "
            "signature in its own validation. A plain signed transfer from an EOA is therefore "
            "the like-for-like cost of an ECDSA account authorizing the same action, and the gap "
            "to our reveal is what the zero-ECDSA machinery (membership proof, nullifier SSTORE, "
            "aging, and the account's own validation) adds on top.\n"
        )
        out.append("| action | ECDSA DefaultAccount | QCA reveal (depth 16) | overhead |")
        out.append("|---|---|---|---|")
        out.append(f"| authorization only (0-value) | {fmt(ba)} | {fmt(ra)} | {ra / ba:.1f}x |")
        out.append(f"| 1 ETH transfer | {fmt(bx)} | {fmt(rx)} | {rx / bx:.1f}x |")
        out.append("")
        out.append(
            "The honest read is not that zero-ECDSA is cheaper. It is the same order of magnitude "
            "as a signed transfer, so the authorization can be made post-quantum without an "
            "ECDSA fallback at a bounded, small-multiple cost, on a live native-AA platform. The "
            "commit is a separate prior transaction (see the table above); this row compares the "
            "reveal against the single ECDSA transaction it replaces.\n"
        )

    # Per-level slope from the two widest depths, for the scaling claim.
    lo, hi = keys[0], keys[-1]
    span = int(hi) - int(lo)
    auth_slope = (
        int(depths[hi]["authOnly"]["revealGasUsed"]) - int(depths[lo]["authOnly"]["revealGasUsed"])
    ) / span
    out.append(
        f"Commit is depth-independent (it stores one mapping entry). The reveal carries the "
        f"Merkle proof, so it grows about {auth_slope:.0f} gas per tree level "
        f"(one keccak plus the proof word), a small linear term on a large fixed base. The "
        f"1 ETH action row adds a value-bearing external call on top of the authorization-only "
        f"reveal.\n"
    )

    out.append("## What ran\n")
    out.append(
        "Per depth and flow: deploy the account via `createAccount` (so it is registered as "
        "an AA account), fund it, post a commit, advance chain time past `minCommitAge`, then "
        "send the reveal as a type-0x71 transaction whose `customSignature` carries "
        "`(leafIndex, secret, proof, maxFeeCap, callGasFloor)`. Every reveal returned status 1. "
        "Transaction hashes are in `qca-zksync-receipts.json`; the run is deterministic "
        "(fixed secrets), so re-running reproduces the same hashes and gas.\n"
    )

    (RESULTS / "RESULTS.md").write_text("\n".join(out))
    print("\n".join(out))


if __name__ == "__main__":
    main()
