// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {CommitRevealAccount} from "../src/CommitRevealAccount.sol";

/// Asserts that the Rust tooling (qca-core) and the contract compute
/// byte-identical hashes. The fixture is generated by
/// `cargo run -p qca-cli -- vectors --depth 3 > contracts/test/vectors/golden.json`
/// and committed; any drift between the two implementations fails here.
contract GoldenVectorsTest is Test {
    bytes32 constant TAG_LEAF = keccak256("QCA/v1/leaf");
    bytes32 constant TAG_NODE = keccak256("QCA/v1/node");
    bytes32 constant TAG_ACTION = keccak256("QCA/v1/action");
    bytes32 constant TAG_COMMIT = keccak256("QCA/v1/commit");

    string json;

    function setUp() public {
        json = vm.readFile("test/vectors/golden.json");
    }

    function test_domainTagsMatch() public view {
        assertEq(vm.parseJsonBytes32(json, ".tag_secret"), keccak256("QCA/v1/secret"));
        assertEq(vm.parseJsonBytes32(json, ".tag_leaf"), TAG_LEAF);
        assertEq(vm.parseJsonBytes32(json, ".tag_node"), TAG_NODE);
        assertEq(vm.parseJsonBytes32(json, ".tag_action"), TAG_ACTION);
        assertEq(vm.parseJsonBytes32(json, ".tag_commit"), TAG_COMMIT);
    }

    function test_leavesAndRootMatch() public view {
        uint256 depth = vm.parseJsonUint(json, ".depth");
        uint256 n = 1 << depth;
        bytes32[] memory level = new bytes32[](n);
        for (uint256 i = 0; i < n; ++i) {
            string memory base = string.concat(".leaves[", vm.toString(i), "]");
            bytes32 secret = vm.parseJsonBytes32(json, string.concat(base, ".secret"));
            bytes32 leaf = keccak256(abi.encode(TAG_LEAF, secret));
            assertEq(leaf, vm.parseJsonBytes32(json, string.concat(base, ".leaf")), "leaf mismatch");
            level[i] = leaf;
        }
        while (level.length > 1) {
            bytes32[] memory next = new bytes32[](level.length / 2);
            for (uint256 i = 0; i < next.length; ++i) {
                next[i] = keccak256(abi.encode(TAG_NODE, level[2 * i], level[2 * i + 1]));
            }
            level = next;
        }
        assertEq(level[0], vm.parseJsonBytes32(json, ".root"), "root mismatch");
    }

    function test_exampleCommitmentMatches() public view {
        address account = vm.parseJsonAddress(json, ".example_account");
        address target = vm.parseJsonAddress(json, ".example_target");
        uint256 value = vm.parseJsonUint(json, ".example_value");
        bytes memory data = vm.parseJsonBytes(json, ".example_data");
        uint256 leafIndex = vm.parseJsonUint(json, ".example_leaf_index");
        uint256 chainId = vm.parseJsonUint(json, ".example_chain_id");
        bytes32 secret =
            vm.parseJsonBytes32(json, string.concat(".leaves[", vm.toString(leafIndex), "].secret"));

        bytes32 actionHash = keccak256(abi.encode(TAG_ACTION, target, value, keccak256(data)));
        assertEq(actionHash, vm.parseJsonBytes32(json, ".example_action_hash"), "action hash mismatch");

        bytes32 c = keccak256(abi.encode(TAG_COMMIT, chainId, account, actionHash, leafIndex, secret));
        assertEq(c, vm.parseJsonBytes32(json, ".example_commitment"), "commitment mismatch");
    }

    /// The strongest form of the check: material produced by the Rust
    /// tooling drives a real account through commit and reveal on-chain.
    function test_rustProofsExecuteOnChain() public {
        uint256 depth = vm.parseJsonUint(json, ".depth");
        bytes32 root = vm.parseJsonBytes32(json, ".root");
        CommitRevealAccount account =
            new CommitRevealAccount{value: 1 ether}(root, depth, 4, 64);

        // Track height locally: via-ir legally hoists block.number reads out
        // of the loop, which vm.roll would otherwise invalidate.
        uint256 height = block.number;
        for (uint256 i = 0; i < (1 << depth); ++i) {
            string memory base = string.concat(".leaves[", vm.toString(i), "]");
            bytes32 secret = vm.parseJsonBytes32(json, string.concat(base, ".secret"));
            bytes32[] memory proof = vm.parseJsonBytes32Array(json, string.concat(base, ".proof"));

            address target = address(uint160(0xB0B0 + i));
            bytes32 actionHash = keccak256(abi.encode(TAG_ACTION, target, uint256(1 wei), keccak256("")));
            account.commit(
                keccak256(abi.encode(TAG_COMMIT, block.chainid, address(account), actionHash, i, secret))
            );
            height += 4;
            vm.roll(height);

            (bool ok,) = account.reveal(target, 1 wei, "", i, secret, proof);
            assertTrue(ok, "rust-generated proof rejected by contract");
        }
    }
}
